### ISSUE TITLE
Demo bugs

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1702]
### [BUG] cutting glitches
When saving (being in the menu where you enter new demo name) a cutted demo even if the player is paused it keeps "playing" but in like 0.001 fps.

### [BUG] cutting wrong map
I also noticed that if I cut demos on selfmapped maps they all break. Maybe related to the new hashing algorithms. I removed my maps folder and cutted the demo agian then it worked. So prioritizing downloaded maps should do the thing.

### [BUG] playback speed
If you scroll too increase speed you run into high numbers very fast and thus get performance issues. Maybe slow down scroll speed since we increased the max replay speed a lot.
also slowest demospeed is a bit fast still for the really fast actions.

EDIT: the playback speed is mostly fine. Even 64x on big maps works smooth. The problem was the map [Back in Time 2](https://github.com/ddnet/ddnet-maps/blob/master/types/insane/maps/Back%20in%20Time%202.map) is waayy too hughe. So demos replayed faster than speed 8 on this map can drop your fps lower than 1. Since the map is veeerry long and doesn't even use half the space of the map this is more a map than a client issue.

### [BUG] envelopes sync
Ingame server time resets synced envelopes. In demo it doesn't.
Maps that make use of this look really weird in demo.

### [FEATURE] background updater
It would be nice to see the cutted demo directly without switching directory. Some background job that also loads demo markers would be great. There is a fetcher already but it freezes the client in big folders (https://github.com/ddnet/ddnet/commit/22f278fdb88ec4e2efcc8d7f2586cd4d5aa3f6b1)

- [x] the playbutton always has a pause symbol. (fixed by #1719)

- [x] cutting glitches (fixed by #1739)

- [x] cutting wrong map (fixed by #1777)

- [x] playback speed (might be caused by https://github.com/ddnet/ddnet/issues/1643)

- [ ] envelopes sync

- [x] background updater (ok enough https://github.com/ddnet/ddnet/commit/22f278fdb88ec4e2efcc8d7f2586cd4d5aa3f6b1)

**Comment by ChillerDragon** [comment]
Also the playbutton always has a pause symbol.

**Comment by ChillerDragon** [comment]
If you scroll too increase speed you run into high numbers very fast and thus get performance issues. Maybe slow down scroll speed since we increased the max replay speed a lot.

**Comment by ChillerDragon** [comment]
Also it would be nice to see the cutted demo directly without switching directory. Some background job that also loads demo markers would be great.

**Comment by Learath2** [comment]
> Also the playbutton always has a pause symbol.

#1719 fixes this

**Comment by Learath2** [comment]
> I also noticed that if I cut demos on selfmapped maps they all break. Maybe related to the new hashing algorithms. I removed my maps folder and cutted the demo agian then it worked. So prioritizing downloaded maps should do the thing.

@heinrich5991 can you take a look at this ^^

**Comment by PathosEthosLogos** [comment]
> When saving (being in the menu where you enter new demo name) a cutted demo even if the player is paused it keeps "playing" but in like 0.001 fps.

Can you show a demonstration of this, maybe record and upload the video? Not sure if we can understand this 100%.

**Comment by ChillerDragon** [comment]
@PathosEthosLogos couldn't you reproduce it? Set two cut markers. Pause the demo. Select a name for the demo and wait a bit.

here is the video https://youtu.be/xVF-lK1s14w

**Comment by sirius1242** [comment]
> Ingame server time resets synced envelopes. In demo it doesn't.
> Maps that make use of this look really weird in demo.

like this?
![2019-10-12-12-27-ScreenShot2](https://user-images.githubusercontent.com/32300858/66694948-b2efae80-ecec-11e9-9bdb-45a914c9ec47.png)

**Comment by sirius1242** [comment]
> Ingame server time resets synced envelopes. In demo it doesn't.
> Maps that make use of this look really weird in demo.

I don't know if this problem was solved, but the condition of the image I upload was solved by #1934

**Comment by ChillerDragon** [comment]
@sirius1242 well I don't know if this is longer a demo bug. I just tested it and even in game synchronized envelopes behave the same as unsynchronized. So since demos now reproduce exactly what is displayed in game I will close the issue now. But I still think that removing the sync feature should be considered a bug.

**Comment by sirius1242** [comment]
[this](https://github.com/sirius1242/sirius1242.github.io/blob/master/file_shared/material13.demo) is a infclass demo that have problem which in the picture I uploaded, and I think it may caused by the problem you mentioned, I repaired it in #1934. (I have tried commit fdf2ec37e7e5988ac6f2ceb440ca400cb1f38187, however, it still have problem)
