### ISSUE TITLE
Missing functionality of 0.7 skin settings

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8750]
- [ ] Refresh button (~~see #8770~~)
- [x] Button to open the skins folder externally (https://github.com/ddnet/ddnet/pull/8838)
- [X] Button to save custom skins (see #8828)
- [X] Button to delete custom skins (button exists, but not fully implemented yet) (see #8755)
